name: GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest -n auto --record-mode=all --beat-challenges -ra tests/challenges
