name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: python/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Remove vcr_cassettes directory
        run: rm -rf tests/vcr_cassettes

      - name: Run tests
        run: pytest

      - name: Set environment variables
        run: |
          echo "CI=true" >> $GITHUB_ENV
          echo "PLAIN_OUTPUT=true" >> $GITHUB_ENV
