name: GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        - name: Install test dependencies
  run: pip install -r requirements.txt
  working-directory: tests

      - name: Run pytest
  run: pytest
  working-directory: tests
