name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: ${{ join(sys.exec_prefix, 'bin', 'pytest') }} -n auto --record-mode=all --beat-challenges -ra tests/challenges
